baseURL: https://Dludora.github.io/Dludora_Blog
languageCode: en-us
title: Dludora's Blog
theme: "PaperMod"

params:
    author: Dludora
    env: production
    

    profileMode:
        author: Dludora
        env: production
        enabled: true
        title: "Dludora的个人世界" 
        subtitle: "没什么要说的"
        imageUrl: "/Dludora_Blog/images/头像/Dludora.jpg" # optional
        imageTitle: "Dludora himself" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: SoftWareEG
              url: SoftWareEG
            # - name: MySQL
            #   url: /Dludora_Blog/MySQL
    socialIcons: 
        - name: "github"
          url: "https://github.com/Dludora"
        - name: "email"
          url: "https://outlook.live.com/"
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

    Displays a Scroll-to-Top button in right-bottom corner: true
    ShowShareButtons: false # share button
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    ShowPostNavLinks: false # next suggestion
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    responsiveImages: false
    linkFullImages: true

    editPost:
        URL: "https://github.com/Dludora/Dludora_Blog/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    cover:
        responsiveImages: false
        linkFullImages: true
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: Search
      name:  Search
      url: /search
      weight: 10
    - identifier: Archive
      name: Archive
      url: /archive
    - identifier: Github
      name: Github
      url: https://github.com/Dludora/Dludora_Blog
      weight: 30